In [1]:
from google.colab import files
import zipfile
import os


print("upload zip")
uploaded = files.upload()

for fn in uploaded.keys():
  zip_filename = fn
  print(f'User uploaded file "{zip_filename}" with length {len(uploaded[fn])} bytes')

extraction_path = './'

with zipfile.ZipFile(zip_filename, 'r') as zip_ref:
    zip_ref.extractall(extraction_path)

print(f'Successfully extracted "{zip_filename}" to "{extraction_path}"')

upload zip

Saving dataset.zip to dataset.zip
User uploaded file "dataset.zip" with length 87162674 bytes
Successfully extracted "dataset.zip" to "./"

In [2]:
import os
import pandas as pd

IMG_DIR_0 = './dataset/images/0'
IMG_DIR_1 = './dataset/images/1'

Pic_files_0 = [os.path.join(IMG_DIR_0, f) for f in os.listdir(IMG_DIR_0) if os.path.isfile(os.path.join(IMG_DIR_0, f))]
Pic_files_1 = [os.path.join(IMG_DIR_1, f) for f in os.listdir(IMG_DIR_1) if os.path.isfile(os.path.join(IMG_DIR_1, f))]

Pic_files = Pic_files_0 + Pic_files_1

print("Total number of image files found:",len(Pic_files))
print("\n🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥\n")
for i in range(5):
    print(Pic_files[i])

print("\n🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥\n")

#JSON FIle
df_json = pd.read_json('/content/dataset/pavbhaji.json')


print("5 rows of JSON ")
display(df_json.head())

print("\n🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥\n")

print("DataFrame Info:")
df_json.info()

Total number of image files found: 452

🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥

./dataset/images/0/39573201_475483916264791_766085791804817408_n.jpg
./dataset/images/0/38911299_283233268937628_7418824802837725184_n.jpg
./dataset/images/0/39276576_320799245135828_6476707577383092224_n.jpg
./dataset/images/0/38716073_1835134429867808_4795041907382319200_n.jpg
./dataset/images/0/40092154_2171536229838011_4987697065023766528_n.jpg

🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥

5 rows of JSON

,dimensions,display_url,edge_liked_by,edge_media_preview_like,edge_media_to_caption,edge_media_to_comment,id,is_video,location,owner,shortcode,tags,taken_at_timestamp,thumbnail_resources,thumbnail_src,urls,video_view_count,comments_disabled
0,"{'height': 734, 'width': 640}",https://instagram.fpnq3-1.fna.fbcdn.net/vp/352...,{'count': 3797},{'count': 3797},{'edges': [{'node': {'text': 'TAG A PAV BHAJI ...,{'count': 52},1834712933156555776,True,None,{'id': '1919686029'},Bl2NbElnIva,"[vadapav, foodgram, foodphotography, foodblogg...",1532934873,"[{'config_height': 150, 'config_width': 150, '...",https://instagram.fpnq3-1.fna.fbcdn.net/vp/cb5...,[https://instagram.fpnq3-1.fna.fbcdn.net/vp/89...,0.0,NaN
1,"{'height': 750, 'width': 750}",https://instagram.fpnq3-1.fna.fbcdn.net/vp/b0d...,{'count': 12041},{'count': 12041},{'edges': [{'node': {'text': 'देसी स्टाइल पाव ...,{'count': 325},1826000656302706176,True,"{'has_public_page': True, 'id': '245717485', '...",{'id': '1445587278'},BlXQewejY3Z,"[healthyfood, sokolkata, mumbaifoodie, faridab...",1531897016,"[{'config_height': 150, 'config_width': 150, '...",https://instagram.fpnq3-1.fna.fbcdn.net/vp/ad3...,[https://instagram.fpnq3-1.fna.fbcdn.net/vp/9c...,0.0,NaN
2,"{'height': 800, 'width': 640}",https://instagram.fpnq3-1.fna.fbcdn.net/vp/cb4...,{'count': 3544},{'count': 3544},{'edges': [{'node': {'text': 'Pav Bhaji😍😍😋\n.\...,{'count': 18},1849962218902145792,True,"{'has_public_page': True, 'id': '213724095', '...",{'id': '4759392841'},BmsYtYpjkq4,"[foodphotography, mumbaipeople, vascom, delhib...",1534752790,"[{'config_height': 150, 'config_width': 150, '...",https://instagram.fpnq3-1.fna.fbcdn.net/vp/64f...,[https://instagram.fpnq3-1.fna.fbcdn.net/vp/5e...,0.0,NaN
3,"{'height': 937, 'width': 750}",https://instagram.fpnq3-1.fna.fbcdn.net/vp/180...,{'count': 1388},{'count': 1388},{'edges': [{'node': {'text': 'Asli Makhan Pav ...,{'count': 91},1828963273137213696,True,"{'has_public_page': True, 'id': '234730336', '...",{'id': '4628040416'},BlhyGgalFDw,"[foodvideo, misscravingbuster, foodblogger, mu...",1532249632,"[{'config_height': 150, 'config_width': 150, '...",https://instagram.fpnq3-1.fna.fbcdn.net/vp/802...,[https://instagram.fpnq3-1.fna.fbcdn.net/vp/33...,0.0,NaN
4,"{'height': 936, 'width': 750}",https://instagram.fpnq3-1.fna.fbcdn.net/vp/5ee...,{'count': 223},{'count': 223},{'edges': [{'node': {'text': 'Tag a Pav bhaji ...,{'count': 14},1852265507774756864,True,None,{'id': '7798081590'},Bm0kapkn3ha,[],1535027282,"[{'config_height': 150, 'config_width': 150, '...",https://instagram.fpnq3-1.fna.fbcdn.net/vp/292...,[https://instagram.fpnq3-1.fna.fbcdn.net/vp/6a...,0.0,NaN

🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   dimensions               1500 non-null   object
 1   display_url              1500 non-null   object
 2   edge_liked_by            1500 non-null   object
 3   edge_media_preview_like  1500 non-null   object
 4   edge_media_to_caption    1500 non-null   object
 5   edge_media_to_comment    1500 non-null   object
 6   id                       1500 non-null   int64
 7   is_video                 1500 non-null   bool
 8   location                 924 non-null    object
 9   owner                    1500 non-null   object
 10  shortcode                1500 non-null   object
 11  tags                     1499 non-null   object
 12  taken_at_timestamp       1500 non-null   int64
 13  thumbnail_resources      1500 non-null   object
 14  thumbnail_src            1500 non-null   object
 15  urls                     1500 non-null   object
 16  video_view_count         110 non-null    float64
 17  comments_disabled        1491 non-null   float64
dtypes: bool(1), float64(2), int64(2), object(13)
memory usage: 200.8+ KB

In [3]:
def extract_caption_text(caption_data):
    if isinstance(caption_data, dict) and 'edges' in caption_data:
        for edge in caption_data['edges']:
            if 'node' in edge and 'text' in edge['node']:
                return edge['node']['text']
    return ''

#new 'caption_text' column
df_json['caption_text'] = df_json['edge_media_to_caption'].apply(extract_caption_text)

#Convert tags list to a single string, handling missing values
df_json['tags_text'] = df_json['tags'].apply(lambda x: ' '.join(x) if isinstance(x, list) else '')


df_json['image_id'] = df_json['shortcode']

display(df_json[['image_id', 'caption_text', 'tags_text']].head())

,image_id,caption_text,tags_text
0,Bl2NbElnIva,TAG A PAV BHAJI FANATIC 😋😍 PC @exploringplates...,vadapav foodgram foodphotography foodblogger m...
1,BlXQewejY3Z,देसी स्टाइल पाव भाजी/Desi Style Paav Bhaji 🇮🇳 ...,healthyfood sokolkata mumbaifoodie faridabad i...
2,BmsYtYpjkq4,Pav Bhaji😍😍😋\n.\nFollow @street_food_chandigar...,foodphotography mumbaipeople vascom delhiboy p...
3,BlhyGgalFDw,Asli Makhan Pav bhaji 😍😋\nTag someone who love...,foodvideo misscravingbuster foodblogger mumbai...
4,Bm0kapkn3ha,Tag a Pav bhaji lover 👇🏻 😋😋,

In [4]:
import re

def extract_image_filename_and_label(file_path):
    filename = os.path.basename(file_path)
    label = 1 if 'images/1' in file_path else 0
    return filename, label

image_data = []

for file_path in Pic_files:
    filename, label = extract_image_filename_and_label(file_path)
    image_data.append({'image_filename': filename, 'label': label})

df_labels = pd.DataFrame(image_data)

# Drop duplicate image_filename
df_labels.drop_duplicates(subset=['image_filename'], inplace=True)

# Extract the image filename from the 'display_url'
def extract_filename_from_url(url):
    match = re.search(r'/([^/]+\.jpg)$', url)
    if match:
        return match.group(1)
    return None

df_json['image_filename'] = df_json['display_url'].apply(extract_filename_from_url)


df_json['text_feature'] = df_json['caption_text'].fillna('') + ' ' + df_json['tags_text'].fillna('')

#Merge df_json with df_label
df_json_labeled = pd.merge(df_json, df_labels, on='image_filename', how='left')


if 'label_x' in df_json_labeled.columns:
    df_json_labeled = df_json_labeled.drop(columns=['label_x'])


if 'label_y' in df_json_labeled.columns:
    df_json_labeled = df_json_labeled.rename(columns={'label_y': 'label'})

df_json_labeled['label'] = df_json_labeled['label'].fillna(0).astype(int)






display(df_json_labeled[['image_id', 'text_feature', 'label']].head())

print("\n🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥\n")
print(f"\nNumber of Pav Bhaji (label=1) entries: {df_json_labeled['label'].sum()}")
print(f"Number of Non-Pav Bhaji (label=0) entries: {len(df_json_labeled) - df_json_labeled['label'].sum()}")
print("\n🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥\n")
print("Here it is clear that data in not balanced for the approach i am using,i'll try to balance it with with one or other way")

      image_id                                       text_feature  label
0  Bl2NbElnIva  TAG A PAV BHAJI FANATIC 😋😍 PC @exploringplates...      0
1  BlXQewejY3Z  देसी स्टाइल पाव भाजी/Desi Style Paav Bhaji 🇮🇳 ...      0
2  BmsYtYpjkq4  Pav Bhaji😍😍😋\n.\nFollow @street_food_chandigar...      0
3  BlhyGgalFDw  Asli Makhan Pav bhaji 😍😋\nTag someone who love...      0
4  Bm0kapkn3ha                       Tag a Pav bhaji lover 👇🏻 😋😋       0

🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥


Number of Pav Bhaji (label=1) entries: 183
Number of Non-Pav Bhaji (label=0) entries: 1317

🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥🚥

Here it is clear that data in not balanced for the approach i am using,i'll try to balance it with with one or other way

In [5]:
#Text Pre Processing
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import re


nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')

stop_words = set(stopwords.words('english'))

def preprocess_text(text):
    text = str(text).lower()  #lowercase
    text = re.sub(r'[^a-z0-9\s]', '', text) #punctuation and special characters
    tokens = word_tokenize(text)
    filtered_tokens = [word for word in tokens if word not in stop_words]
    return ' '.join(filtered_tokens)

df_json_labeled['processed_text'] = df_json_labeled['text_feature'].apply(preprocess_text)

print("Processed Text")
display(df_json_labeled[['text_feature', 'processed_text', 'label']].sample(10))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

Processed Text

,text_feature,processed_text,label
381,Cheese butter Pav Bhaji Dosa- Street style at ...,cheese butter pav bhaji dosa street style hira...,0
1490,The perfect way to eat pav bhaji!\n#foodporn #...,perfect way eat pav bhaji foodporn foodgasm pa...,0
882,Having “PAV BHAJI” any time of the day? Well h...,pav bhaji time day well hell yeah never ignore...,0
513,*NEW TESTIMONI*\n🧡 Alhamdulillah Positif 🧡 *21...,new testimoni alhamdulillah positif 21 agustus...,0
868,"Yeh dekh, main bas itna hi samajh paya ki zind...",yeh dekh main bas itna hi samajh paya ki zinda...,0
253,"तुम्हें अपना बनाने की कसम खाई है, खाई है ♥️ लो...",note9 delhidiaries kolkata foodpic foodstyle i...,0
78,Pav Bhaji - Creamy potato & veggie slurry with...,pav bhaji creamy potato veggie slurry crunchy ...,0
146,#pavbhaji pavbhaji,pavbhaji pavbhaji,1
582,Khana hai tumhe; aa jao. Sath mai khate hai 😋 ...,khana hai tumhe aa jao sath mai khate hai indi...,0
1428,#pavbhaji #cheezpavbhaji #pavbhaji😋 #foodlover...,pavbhaji cheezpavbhaji pavbhaji foodlovers pav...,0

In [6]:
df_json_labeled['processed_text'] = df_json_labeled['text_feature'].apply(preprocess_text)

print("First 5 rows with processed text:")
display(df_json_labeled[['text_feature', 'processed_text', 'label']].head())

First 5 rows with processed text:

,text_feature,processed_text,label
0,TAG A PAV BHAJI FANATIC 😋😍 PC @exploringplates...,tag pav bhaji fanatic pc exploringplates food ...,0
1,देसी स्टाइल पाव भाजी/Desi Style Paav Bhaji 🇮🇳 ...,desi style paav bhaji good afternoon instafami...,0
2,Pav Bhaji😍😍😋\n.\nFollow @street_food_chandigar...,pav bhaji follow streetfoodchandigarh use stre...,0
3,Asli Makhan Pav bhaji 😍😋\nTag someone who love...,asli makhan pav bhaji tag someone loves creamc...,0
4,Tag a Pav bhaji lover 👇🏻 😋😋,tag pav bhaji lover,0

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer


tfidf_vectorizer = TfidfVectorizer(max_features=5000) 


X = tfidf_vectorizer.fit_transform(df_json_labeled['processed_text'])


tfidf_feature_names = tfidf_vectorizer.get_feature_names_out()

print(f"Shape of TF-IDF features (X): {X.shape}")
print(f"First 10 TF-IDF feature names: {tfidf_feature_names[:10]}")

y = df_json_labeled['label']
print(f"Shape of labels (y): {y.shape}")

Shape of TF-IDF features (X): (1500, 5000)
First 10 TF-IDF feature names: ['10' '100' '1000' '100000likes' '1000likes' '100happydays' '10k' '11'
 '110' '11th']
Shape of labels (y): (1500,)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")


model = LogisticRegression(random_state=42, solver='liblinear') 
model.fit(X_train, y_train)


y_pred = model.predict(X_test)

#Evaluate model
accuracy = accuracy_score(y_test, y_pred)
print(f"\nModel Accuracy: {accuracy:.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

X_train shape: (1200, 5000)
X_test shape: (300, 5000)
y_train shape: (1200,)
y_test shape: (300,)

Model Accuracy: 0.8767

Classification Report:
              precision    recall  f1-score   support

           0       0.88      1.00      0.93       263
           1       0.00      0.00      0.00        37

    accuracy                           0.88       300
   macro avg       0.44      0.50      0.47       300
weighted avg       0.77      0.88      0.82       300

/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [9]:
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, accuracy_score
import numpy as np

RANDOM_STATE = 42

neg_count = np.sum(y_train == 0)
pos_count = np.sum(y_train == 1)
scale_pos_weight_value = neg_count / pos_count
print(f"Calculated scale_pos_weight: {scale_pos_weight_value:.2f}")

xgb_model = XGBClassifier(
    objective='binary:logistic',
    eval_metric='logloss',
    random_state=RANDOM_STATE,
    scale_pos_weight=scale_pos_weight_value,
    use_label_encoder=False
)

xgb_model.fit(X_train, y_train)


y_pred_xgb = xgb_model.predict(X_test)

#Evaluate the XGBoost model
accuracy_xgb = accuracy_score(y_test, y_pred_xgb)
print(f"\nXGBoost Model Accuracy: {accuracy_xgb:.4f}")
print("\nXGBoost Classification Report:")
print(classification_report(y_test, y_pred_xgb))

Calculated scale_pos_weight: 7.22

/usr/local/lib/python3.13/dist-packages/xgboost/training.py:200: UserWarning: [13:45:33] WARNING: /__w/xgboost/xgboost/src/learner.cc:794:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

XGBoost Model Accuracy: 0.8433

XGBoost Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.94      0.91       263
           1       0.25      0.14      0.18        37

    accuracy                           0.84       300
   macro avg       0.57      0.54      0.54       300
weighted avg       0.81      0.84      0.82       300